#!/bin/bash

# Wait for Postgres to be ready and generate the configuration
/usr/local/bin/dockerize \
  -wait tcp://postgres:5432 \
  -template /xnat/config.tmpl:/xnat/config \
  /bin/true

# Check if the webapp has been installed, otherwise launch the installer
. /xnat/config
if [ -z "$project_name" -o ! -d /usr/local/tomcat/webapps/$project_name ]
then
    /builder/xnat-installer/bin/build /xnat
fi

/usr/local/tomcat/bin/startup.sh

tail -f /usr/local/tomcat/logs/catalina.out

# eof
